name: Update README Activity

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Activity Section
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} 
        with:
          COMMIT_MSG: "sys: updated recent activity history [skip ci]"
          MAX_LINES: 15
          # This explicitly includes your code commits (PushEvent)
          FILTER_EVENTS: PushEvent,PullRequestEvent,IssuesEvent,ReleaseEvent,IssueCommentEvent
